---
- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
  notify: Restart dockerd service
