---
- name: Download file get-pip.py
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/pip/3.5/get-pip.py
    dest: /tmp/get-pip.py
    mode: "0644"

- name: Add host to hosts file
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: |
      {% for host in groups['baremetal']  %}
      {% set iface = 'ansible_' + internal_interface  %}
      {{ hostvars[host][iface].ipv4.address }} {{ hostvars[host].ansible_hostname }}
      {% endfor %}
    insertafter: EOF
  become: true

- name: Ensure apt sources list directory exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    recurse: true
  become: true

- name: Add Docker apt repository
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_url }}/gpg"
    state: present
  become: true
